<a href="https://colab.research.google.com/github/limetimeline/ML_Study/blob/main/ML_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
a = np.array([1,2,3])
a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [ ]:
sal = np.array([240, 260, 220, 255])

In [ ]:
sal = sal + 100
print(sal)

[340 360 320 355]


In [ ]:
scores = np.array([58, 72, 93, 94, 89, 78, 99])
scores[3:] # Index 3부터...

array([94, 89, 78, 99])

In [ ]:
scores[4:-1] # Index 4부터 끝 앞까지

array([89, 78])

In [ ]:

scores[-1] # 사실 -1은 끝인 99임.

99

In [ ]:
np_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np_array[0,2]

3

In [ ]:
np_array = np.array([[1,2,3,4],[5,6,7,8],
                     [9,10,11,12], [13,14,15,16]])
np_array[0:2, 2:4] # (0,1) x (2,3)
# [[0,2], [0,3]], [[1,2], [1,3]]

array([[3, 4],
       [7, 8]])

In [ ]:
np_array[0:2][2:4]
# 1. [0:2]부터 실행. 그럼 [[1,2,3,4], [5,6,7,8]]배열 생성.
# 2. [2:4]를 실행. 근데 문제는 0, 1행은 있는데 2~3행은 존재하지 않음.
# 3. 빈 배열 생성

array([], shape=(0, 4), dtype=int64)